### ISSUE TITLE
Errors with PVAClone 0.1-4

### ISSUE THREAD

**Issue by tmhegel** [psolymos/PVAClone#1]
Hello Peter,

I recently installed PVAClone 0.1-4. I am using R (3.2.3) on a 32-bit machine (Windows 7). I am trying to run some of the examples in the help files, with the accompanying package datasets but am receiving these errors. Code and errors are provided below (one using each of the three package datasets). Any advice you may have would be greatly appreciated. It's entirely possible I am missing something obvious. The third example is quite strange because in the paurelia dataset the first and last observations are not NA.

Troy

---

> m1 <- pva(songsparrow, gompertz("none"), 2, n.iter=1000)
> ERROR:
> no method or default for coercing "dcmle" to "mcmc.list"

and,

m1 <- pva(redstart, "gompertz", c(5,10))
ERROR:
no method or default for coercing "dcmle" to "mcmc.list"

and, 

m1na <- pva(paurelia, "gompertz", c(5,10))
ERROR:
first and last observation must not be NA

**Comment by psolymos** [comment]
Thanks for reporting @tmhegel ! In the past days I was messing around S4 classes in the dcmle package which caused the issue. Fix is on the way.

**Comment by psolymos** [comment]
eced54634ca316049b91c27a1ff18ab50137434d closes this issue.

CRAN update will take for a while (need to introduce version dependency that is error prone), in the meantime please update from github:

```
library(devtools)
install_github("datacloning/dcmle")
install_github("psolymos/PVAClone")
```

All 3 examples run fine now.

**Comment by tmhegel** [comment]
Hi Peter,

Thank you for your incredibly fast response. I reinstalled the two packages from GitHub and have tried to run the examples again, but (and you may come to hate me for this), I still get some errors. The same error with the paurelia dataset is coming up, but now with the redstart and songsparrow datasets it appears as if the models are run, but then I get this invalid pva class error.

Cheers

Troy

m1 <- pva(redstart, "gompertz", c(5,10))

ERROR:
invalid class "pva" object

m1na <- pva(paurelia, "ricker", c(5,10))

ERROR:
first and last observation must not be NA

m1 <- pva(songsparrow, "thetalogistic", c(5,10))

ERROR:
invalid class "pva" object

**Comment by psolymos** [comment]
Hmm. It works for me. Can you send me your `sessionInfo()` and `traceback()` after the error?

**Comment by tmhegel** [comment]
Hello Peter,

Here is my sessionInfo:

> sessionInfo()
> R version 3.2.3 (2015-12-10)
> Platform: i386-w64-mingw32/i386 (32-bit)
> Running under: Windows 7 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252
[2] LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] splines   stats4    parallel  stats     graphics  grDevices utils
 [8] datasets  methods   base

other attached packages:
[1] Rcmdr_2.2-3     RcmdrMisc_1.0-3 sandwich_2.3-4  car_2.1-1
[5] PVAClone_0.1-5  dcmle_0.3-1     dclone_2.1-1    Matrix_1.2-3
[9] coda_0.18-1

loaded via a namespace (and not attached):
[1] Formula_1.2-1       minqa_1.2.4         ggplot2_2.0.0
 [4] class_7.3-14        tcltk_3.2.3         lattice_0.20-33
 [7] foreign_0.8-66      snow_0.4-1          pbkrtest_0.4-4
[10] readxl_0.1.0        SparseM_1.7         Rcpp_0.12.3
[13] gridExtra_2.0.0     plyr_1.8.3          tools_3.2.3
[16] MASS_7.3-45         nlme_3.1-122        zoo_1.7-12
[19] scales_0.3.0        MatrixModels_0.4-1  nnet_7.3-11
[22] lme4_1.1-10         gtable_0.1.2        latticeExtra_0.6-26
[25] cluster_2.0.3       rjags_4-5           rpart_4.1-10
[28] munsell_0.4.2       grid_3.2.3          colorspace_1.2-6
[31] quantreg_5.19       nloptr_1.0.4        tcltk2_1.2-11
[34] Hmisc_3.17-1        survival_2.38-3     mgcv_1.8-10
[37] e1071_1.6-7         RColorBrewer_1.1-2  acepack_1.3-3.3
[40] abind_1.4-3

---

Here is one example:

> m1 <- pva(redstart, "gompertz", c(5,10))

Fitting model with 5 clones

Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 5
   Unobserved stochastic nodes: 3
   Total graph size: 192

Initializing model

  |
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100%

  |*************************************************_| 100%
  |**_***********************************************| 100%
Error in chol.default(W) :
  the leading minor of order 4 is not positive definite

Fitting model with 10 clones

Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 10
   Unobserved stochastic nodes: 3
   Total graph size: 342

Initializing model
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100%
  |*************************************************_| 100%
  |**_***********************************************| 100%
Error in chol.default(W) :
  the leading minor of order 4 is not positive definite
Warning in dclone::.dcFit(data, params, model, inits, n.clones, multiply = multiply,  :
  chains convergence problem, see R.hat values
Error in validObject(.Object) :
  invalid class "pva" object: invalid object for slot "observations" in class "pva": got class "data.frame", should be or extend class "numeric"

> traceback()
> 6: stop(msg, ": ", errors, domain = NA)
> 5: validObject(.Object)
> 4: initialize(value, ...)
> 3: initialize(value, ...)
> 2: new("pva", fit, summary = s, observations = x, model = model)
> 1: pva(redstart, "gompertz", c(5, 10))

---

Here is a second example:

> m1na <- pva(paurelia, "gompertz", c(5,10))
> Error in pva(paurelia, "gompertz", c(5, 10)) :
>   first and last observation must not be NA
> traceback()
> 2: stop("first and last observation must not be NA")
> 1: pva(paurelia, "gompertz", c(5, 10))

---

I hope this might shed some light on what is going on with things at least on my end. Thank you so much for looking into this.

Cheers

Troy

Troy Hegel
Ungulate Biologist (Caribou, Sheep and Goats)
Environment Yukon
Fish and Wildlife Branch
P: (867) 667-5465
F: (867) 393-6263
Troy.Hegel@gov.yk.ca

**Comment by psolymos** [comment]
I tested the package on Windows and works all the same. It seems to me that something funny is going on with the data. Here is what I see when looking at the `str()`:

```
> str(songsparrow)
 num [1:24] 35 31 45 48 66 9 19 26 54 53 ...
> str(redstart)
 num [1:30] 18 10 9 14 17 14 5 10 9 5 ...
> str(paurelia)
 num [1:20] 2 NA 17 29 39 63 185 258 267 392 ...
```

Can you do the same? Also please try supplying the data `as.numeric`:

```
m1 <- pva(as.numeric(redstart), "gompertz", c(5,10))
```

I added a check to enforce this (see 491cffce286bdb03ab3675e73a794d02b879b676).

**Comment by tmhegel** [comment]
Hi Peter,

I tried your suggestions. Here is what I got back.

str(songsparrow)
'data.frame':      24 obs. of  1 variable:
$ songsparrow: num  35 31 45 48 66 9 19 26 54 53 ...

> str(redstart)
> 'data.frame':      30 obs. of  1 variable:
> $ redstart: num  18 10 9 14 17 14 5 10 9 5 ...
> 
> str(paurelia)
> 'data.frame':      20 obs. of  1 variable:
> $ paurelia: num  2 NA 17 29 39 63 185 258 267 392 ...
> 
> m1 <- pva(as.numeric(redstart), "gompertz", c(5,10))
> Error in pva(as.numeric(redstart), "gompertz", c(5, 10)) :
>   (list) object cannot be coerced to type 'double'

Regards,

Troy

**Comment by psolymos** [comment]
Somehow the data (which is supposed to be a numeric vector) is turned into a data frame. 

How about:

```
m <- pva(as.numeric(unlist(redstart)), "gompertz", c(5,10))
```

**Comment by tmhegel** [comment]
Success!!!

This now works fine. I tried one of your examples for each of the three datasets and the model runs for all of them.

Thank you very much for your help on this. I am looking forward to working with your package on some wild sheep numbers from here in the Yukon.

Cheers

Troy

**Comment by psolymos** [comment]
Glad it worked! I still have no idea what was going on (I tried installing different versions but example data was never a data frame for me).
